language: node_js
node_js:
  - "node"

before_deploy:
  - zip -r Paladin * -x *.git* -x "node_modules/*" || true
  - mkdir -p upload
  - mv Paladin.zip upload/Paladin.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: upload
    skip_cleanup: true
    bucket: "polaris.paladin.deploy"
    region: us-east-2
    on:
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "polaris.paladin.deploy"
    key: Paladin.zip
    bundle_type: zip
    application: Paladin
    deployment_group: Paladin-Production
    region: us-east-2
    on:
      branch: master
 - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: upload
    skip_cleanup: true
    bucket: "polaris.paladin.development.deploy"
    region: us-east-2
    on:
      branch: develop
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "polaris.paladin.development.deploy"
    key: Paladin.zip
    bundle_type: zip
    application: Paladin
    deployment_group: Paladin-Development
    region: us-east-2
    on:
      branch: develop
notifications:
  slack: polarislabs:fGkXWORxxoqtsiBAAFApzeEM
