version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Paladin
hooks:
  AfterInstall:
    - location: post_install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: start.sh
      timeout: 120
      runas: ubuntu
  ValidateService:
    - location: validate.sh
      timeout: 180
      runas: ubuntu
