version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Paladin
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  AfterInstall:
    - location: deployment/post_install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: deployment/start.sh
      timeout: 120
      runas: ubuntu
  ValidateService:
    - location: deployment/validate.sh
      timeout: 180
      runas: ubuntu
